default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: mixed-line-ending
        args:
          - --fix=no
      - id: check-added-large-files
        args:
          - --maxkb=2048
      - id: trailing-whitespace
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id : isort
        args : ["--profile=black", "--filter-files"]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b0]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings, Flake8-pyproject]

  - repo: https://github.com/numpy/numpydoc
    rev: v1.6.0
    hooks:
      - id: numpydoc-validation
